#!/usr/bin/env bash

echo "running pre-commit hook"

export PATH=/usr/local/bin:$PATH

# Copy Paste Detector - https://github.com/kucherenko/jscpd

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.jsx\?$')
BIN_PATH="$(git rev-parse --show-toplevel)/node_modules/.bin"

eslint() {
	ESLINT="$BIN_PATH/eslint"

	# Check for eslint
	if [[ ! -x "$ESLINT" ]]; then
		printf "\tPlease install ESLint\n"
		exit 1
	fi

	echo "Linting modified files"

	echo $STAGED_FILES | xargs $ESLINT

	if [[ $? == 0 ]]; then
		printf "\nLint Passed\n"
	else
		printf "\nLint Failed: Fix lint errors and try again!\n"
		exit 1
	fi
}

jest() {
	JEST="$BIN_PATH/jest"

	# Check for jest
	if [[ ! -x "$JEST" ]]; then
		printf "\tPlease install Jest\n"
		exit 1
	fi

	echo "Testing related to modified files"

	$JEST --bail --findRelatedTests $STAGED_FILES

	if [[ $? == 0 ]]; then
		printf "\nTest Passed\n"
	else
		printf "\nTest Failed: Fix test errors and try again!\n"
		exit 1
	fi
}

# Exit if no files modified
if [[ "$STAGED_FILES" = "" ]]; then
	exit 0
fi

jest
eslint

exit $?
